version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # node-app:
  #   image: travel-app-server:latest
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   env_file: ./.env
  #   # ports:
  #   #   - "3000:3000"
  #   depends_on:
  #     - postgres

volumes:
  pg_data:
  backend_node_modules:
