#Định nghĩa version, tên các service
#Lấy các biến môi trường được định nghĩa tại .env làm các giá trị

version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - $MYSQL_ADMINER_LOCAL_PORT:$MYSQL_ADMINER_DOCKER_PORT

  auth_app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile_Auth
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_AUTH_LOCAL_PORT:$NODE_AUTH_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_LOCAL_PORT
    stdin_open: true
    tty: true

volumes:
  db:
