version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - $MYSQL_ADMINER_LOCAL_PORT:$MYSQL_ADMINER_DOCKER_PORT

  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  auth_app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    ports:
      - $NODE_AUTH_LOCAL_PORT:$NODE_AUTH_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  db:
